### ISSUE TITLE
textile to links containing parentheses fails

### ISSUE THREAD

**Issue by hhsprings** [textile/python-textile#20]
See [spec(20 May 2009)](https://github.com/jgarber/redcloth/blob/master/spec/fixtures/links.yml#L220).

```python
>>> import textile
>>> textile.__version__
'2.2.2'
>>> from textile import textile
>>> r = textile('''\
... This is a link to a \
... ["Wikipedia article about Textile":http://en.wikipedia.org/wiki/Textile_(markup_language)].
... ''')
Traceback (most recent call last):
  File "<stdin>", line 4, in <module>
  File "c:\Python27\lib\site-packages\textile\core.py", line 1661, in textile
    head_offset=head_offset)
  File "c:\Python27\lib\site-packages\textile\core.py", line 267, in parse
    text = self.block(text, int(head_offset))
  File "c:\Python27\lib\site-packages\textile\core.py", line 780, in block
    cite, line)
  File "c:\Python27\lib\site-packages\textile\core.py", line 913, in fBlock
    content = self.graf(content)
  File "c:\Python27\lib\site-packages\textile\core.py", line 1105, in graf
    text = self.links(text)
  File "c:\Python27\lib\site-packages\textile\core.py", line 1160, in links
    text = re.compile(pattern, re.X | re.U).sub(self.fLink, text)
  File "c:\Python27\lib\site-packages\textile\core.py", line 1203, in fLink
    out = ''.join([pre, out, post, tail])
TypeError: sequence item 3: expected string or Unicode, NoneType found
>>> 
```
I don't know what is `Textile 2.5` which is mentioned at TODO.textile, but this spec is [at least 8 years old](https://github.com/jgarber/redcloth/blame/master/spec/fixtures/links.yml#L220), so python-textile may have to render this correctly, or at least it should not stop render by Exception but should ignore this markup.

**Comment by ikirudennis** [comment]
This is resolved in the develop branch. It will be merged in soon-ish.
