### ISSUE TITLE
Table build without space after aligment raise a AttributeError.

### ISSUE THREAD

**Issue by tynopet** [textile/python-textile#52]
`textile('|=.First Header |=. Second Header |')` raise a AttributeError.
```
Traceback (most recent call last):
  File "<stdin>", line 1, in <module>
  File "/home/dmitry/.local/lib/python2.7/site-packages/textile/core.py", line 1412, in textile
    return Textile(html_type=html_type).parse(text)
  File "/home/dmitry/.local/lib/python2.7/site-packages/textile/core.py", line 248, in parse
    text = self.block(text)
  File "/home/dmitry/.local/lib/python2.7/site-packages/textile/core.py", line 499, in block
    block = Block(self, tag, atts, ext, cite, line)
  File "/home/dmitry/.local/lib/python2.7/site-packages/textile/objects/block.py", line 32, in __init__
    self.process()
  File "/home/dmitry/.local/lib/python2.7/site-packages/textile/objects/block.py", line 125, in process
    self.content = self.textile.graf(self.content)
  File "/home/dmitry/.local/lib/python2.7/site-packages/textile/core.py", line 641, in graf
    text = self.table(text)
  File "/home/dmitry/.local/lib/python2.7/site-packages/textile/core.py", line 291, in table
    return table.process()
  File "/home/dmitry/.local/lib/python2.7/site-packages/textile/objects/table.py", line 45, in process
    caption = Caption(**cmtch.groupdict())
AttributeError: 'NoneType' object has no attribute 'groupdict'
```

Expected output (from textile sandbox):
```
<table>
		<tr>
			<td>=.<strong>First Header</strong> </td>
			<td style="text-align:center;">Second Header </td>
		</tr>
</table>
```

**Comment by ikirudennis** [comment]
Hi, @tynopet. I'm not getting the `<strong>` tags from txstyle.org, so the output you'll get won't match exact what you expected above. But at least it won't crash.

**Comment by tynopet** [comment]
Oh, I'm sorry, I copying and paste the output from `textile('|=.*First Header* |=. Second Header |')` by mistake. Thank you for fast fixed.
